# Generated by Django 4.2.4 on 2023-08-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyso_itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraries',
            options={'verbose_name_plural': 'Recommendations'},
        ),
    ]
