# Generated by Django 4.2.4 on 2023-08-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyso_recommendations', '0002_alter_recommendations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name_plural': 'Recommendations'},
        ),
    ]
