# Generated by Django 4.2.4 on 2023-08-30 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odyso_itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_data', models.JSONField()),
                ('safety_score', models.IntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyso_itineraries.itineraries')),
            ],
        ),
    ]
