# Generated by Django 4.2.4 on 2023-08-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyso_safety_security', '0002_alter_safetyroutes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetyroutes',
            options={},
        ),
    ]
